#version: '3.3'
web:
   image : 'gitlab/gitlab-ee:latest'
   restart: always
   hostname : '<yourhost>'
   container_name : 'gitlab'
   environment : 
       GITLAB_OMNIBUS_CONFIG : |
          gitlab_rails['gitlab_shell_ssh_port']=2222
   ports :
       - '3000:3000'
       - '2222:22'

   volumes:
       - '/gitlab/config:/etc/gitlab'
       - '/gitlab/logs:/var/log/gitlab'
       - '/gitlab/data:/var/opt/gitlab'
       - './:/backupfiles'
